//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hsrm.DeepModeling.Warehouse.Products.MyWarehouse
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Linq;
    using NMF.Expressions;
    using NMF.Expressions.Linq;
    using NMF.Models;
    using NMF.Models.Meta;
    using NMF.Models.Collections;
    using NMF.Models.Expressions;
    using NMF.Collections.Generic;
    using NMF.Collections.ObjectModel;
    using NMF.Serialization;
    using NMF.Utilities;
    using NMF.Models.Repository;
    using Hsrm.DeepModeling.Warehouse.Warehouse;
    using System.Collections.Specialized;
    
    
    /// <summary>
    /// The default implementation of the Book class
    /// </summary>
    [XmlNamespaceAttribute("https://example.org")]
    [XmlNamespacePrefixAttribute("ex")]
    [ModelRepresentationClassAttribute("https://example.org/#//Book")]
    [DebuggerDisplayAttribute("Book {Name}")]
    public partial class Book : Hsrm.DeepModeling.Warehouse.Warehouse.IndividualProduct, IBook, NMF.Models.IModelElement
    {
        
        /// <summary>
        /// The backing field for the Isbn property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private string _isbn;
        
        private static Lazy<NMF.Models.Meta.ITypedElement> _isbnAttribute = new Lazy<NMF.Models.Meta.ITypedElement>(RetrieveIsbnAttribute);
        
        private static NMF.Models.Meta.IClass _classInstance;
        
        /// <summary>
        /// The isbn property
        /// </summary>
        [DisplayNameAttribute("isbn")]
        [CategoryAttribute("Book")]
        [XmlElementNameAttribute("isbn")]
        [XmlAttributeAttribute(true)]
        public string Isbn
        {
            get
            {
                return this._isbn;
            }
            set
            {
                if ((this._isbn != value))
                {
                    string old = this._isbn;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnIsbnChanging(e);
                    this.OnPropertyChanging("Isbn", e, _isbnAttribute);
                    this._isbn = value;
                    this.OnIsbnChanged(e);
                    this.OnPropertyChanged("Isbn", e, _isbnAttribute);
                }
            }
        }
        
        /// <summary>
        /// Gets the ProductSpecification model for this type
        /// </summary>
        public new static Hsrm.DeepModeling.Warehouse.Warehouse.IProductSpecification ProductSpecificationInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("https://example.org/#//Book")));
                }
                return ((Hsrm.DeepModeling.Warehouse.Warehouse.IProductSpecification)(_classInstance));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static NMF.Models.Meta.IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("https://example.org/#//Book")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired when the Isbn property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> IsbnChanged;
        
        /// <summary>
        /// Gets fired before the Isbn property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> IsbnChanging;
        
        private static NMF.Models.Meta.ITypedElement RetrieveIsbnAttribute()
        {
            return ((NMF.Models.Meta.ITypedElement)(((NMF.Models.ModelElement)(Hsrm.DeepModeling.Warehouse.Products.MyWarehouse.Book.ClassInstance)).Resolve("isbn")));
        }
        
        /// <summary>
        /// Raises the IsbnChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnIsbnChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.IsbnChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the IsbnChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnIsbnChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.IsbnChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "ISBN"))
            {
                return this.Isbn;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "ISBN"))
            {
                this.Isbn = ((string)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "ISBN"))
            {
                return new IsbnProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the ProductSpecification for this model element
        /// </summary>
        public override Hsrm.DeepModeling.Warehouse.Warehouse.IProductSpecification GetProductSpecification()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("https://example.org/#//Book")));
            }
            return ((Hsrm.DeepModeling.Warehouse.Warehouse.IProductSpecification)(_classInstance));
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override NMF.Models.Meta.IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("https://example.org/#//Book")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the isbn property
        /// </summary>
        private sealed class IsbnProxy : ModelPropertyChange<IBook, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public IsbnProxy(IBook modelElement) : 
                    base(modelElement, "isbn")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Isbn;
                }
                set
                {
                    this.ModelElement.Isbn = value;
                }
            }
        }
    }
}
