//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hsrm.DeepModeling.Warehouse.Products.MyWarehouse
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Linq;
    using NMF.Expressions;
    using NMF.Expressions.Linq;
    using NMF.Models;
    using NMF.Models.Meta;
    using NMF.Models.Collections;
    using NMF.Models.Expressions;
    using NMF.Collections.Generic;
    using NMF.Collections.ObjectModel;
    using NMF.Serialization;
    using NMF.Utilities;
    using NMF.Models.Repository;
    using Hsrm.DeepModeling.Warehouse.Warehouse;
    using System.Collections.Specialized;
    
    
    /// <summary>
    /// The default implementation of the DVDPlayer class
    /// </summary>
    [XmlNamespaceAttribute("https://example.org")]
    [XmlNamespacePrefixAttribute("ex")]
    [ModelRepresentationClassAttribute("https://example.org/#//DVDPlayer")]
    [DebuggerDisplayAttribute("DVDPlayer {Name}")]
    public partial class DVDPlayer : Hsrm.DeepModeling.Warehouse.Warehouse.IndividualProduct, IDVDPlayer, NMF.Models.IModelElement
    {
        
        private static NMF.Models.Meta.IClass _classInstance;
        
        /// <summary>
        /// Gets the ProductSpecification model for this type
        /// </summary>
        public new static Hsrm.DeepModeling.Warehouse.Warehouse.IProductSpecification ProductSpecificationInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("https://example.org/#//DVDPlayer")));
                }
                return ((Hsrm.DeepModeling.Warehouse.Warehouse.IProductSpecification)(_classInstance));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static NMF.Models.Meta.IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("https://example.org/#//DVDPlayer")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets the ProductSpecification for this model element
        /// </summary>
        public override Hsrm.DeepModeling.Warehouse.Warehouse.IProductSpecification GetProductSpecification()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("https://example.org/#//DVDPlayer")));
            }
            return ((Hsrm.DeepModeling.Warehouse.Warehouse.IProductSpecification)(_classInstance));
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override NMF.Models.Meta.IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("https://example.org/#//DVDPlayer")));
            }
            return _classInstance;
        }
    }
}
