//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hsrm.DeepModeling.Warehouse.Products.MyWarehouse
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Linq;
    using NMF.Expressions;
    using NMF.Expressions.Linq;
    using NMF.Models;
    using NMF.Models.Meta;
    using NMF.Models.Collections;
    using NMF.Models.Expressions;
    using NMF.Collections.Generic;
    using NMF.Collections.ObjectModel;
    using NMF.Serialization;
    using NMF.Utilities;
    using NMF.Models.Repository;
    using Hsrm.DeepModeling.Warehouse.Warehouse;
    using System.Collections.Specialized;
    
    
    /// <summary>
    /// The public interface for AABatteryCell
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(AABatteryCell))]
    [XmlDefaultImplementationTypeAttribute(typeof(AABatteryCell))]
    [ModelRepresentationClassAttribute("https://example.org/#//AABatteryCell")]
    public interface IAABatteryCell : NMF.Models.IModelElement, Hsrm.DeepModeling.Warehouse.Warehouse.IBulkProduct
    {
    }
}
