//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hsrm.DeepModeling.Warehouse.Products.MyWarehouse
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Linq;
    using NMF.Expressions;
    using NMF.Expressions.Linq;
    using NMF.Models;
    using NMF.Models.Meta;
    using NMF.Models.Collections;
    using NMF.Models.Expressions;
    using NMF.Collections.Generic;
    using NMF.Collections.ObjectModel;
    using NMF.Serialization;
    using NMF.Utilities;
    using NMF.Models.Repository;
    using Hsrm.DeepModeling.Warehouse.Warehouse;
    using System.Collections.Specialized;
    
    
    /// <summary>
    /// The public interface for DVD
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(DVD))]
    [XmlDefaultImplementationTypeAttribute(typeof(DVD))]
    [ModelRepresentationClassAttribute("https://example.org/#//DVD")]
    public interface IDVD : NMF.Models.IModelElement, Hsrm.DeepModeling.Warehouse.Warehouse.IIndividualProduct
    {
        
        /// <summary>
        /// The recommendedPlayer property
        /// </summary>
        [DisplayNameAttribute("recommendedPlayer")]
        [CategoryAttribute("DVD")]
        [XmlElementNameAttribute("recommendedPlayer")]
        [XmlAttributeAttribute(true)]
        IDVDPlayer RecommendedPlayer
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the RecommendedPlayer property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> RecommendedPlayerChanging;
        
        /// <summary>
        /// Gets fired when the RecommendedPlayer property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> RecommendedPlayerChanged;
    }
}
