//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hsrm.DeepModeling.Warehouse.Products.Products
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Linq;
    using NMF.Expressions;
    using NMF.Expressions.Linq;
    using NMF.Models;
    using NMF.Models.Meta;
    using NMF.Models.Collections;
    using NMF.Models.Expressions;
    using NMF.Collections.Generic;
    using NMF.Collections.ObjectModel;
    using NMF.Serialization;
    using NMF.Utilities;
    using NMF.Models.Repository;
    using Hsrm.DeepModeling.Warehouse.Warehouse;
    
    
    /// <summary>
    /// The default implementation of the HaChi779 class
    /// </summary>
    [XmlNamespaceAttribute("https://example.org/products")]
    [XmlNamespacePrefixAttribute("p")]
    [ModelRepresentationClassAttribute("https://example.org/products#//HaChi779")]
    public partial class HaChi779 : Hsrm.DeepModeling.Warehouse.Warehouse.SaleItem, IHaChi779, NMF.Models.IModelElement
    {
        
        /// <summary>
        /// The backing field for the SerialNumber property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private string _serialNumber;
        
        private static Lazy<NMF.Models.Meta.ITypedElement> _serialNumberAttribute = new Lazy<NMF.Models.Meta.ITypedElement>(RetrieveSerialNumberAttribute);
        
        private static NMF.Models.Meta.IClass _classInstance;
        
        /// <summary>
        /// The serialNumber property
        /// </summary>
        [DisplayNameAttribute("serialNumber")]
        [CategoryAttribute("HaChi779")]
        [XmlElementNameAttribute("serialNumber")]
        [XmlAttributeAttribute(true)]
        public string SerialNumber
        {
            get
            {
                return this._serialNumber;
            }
            set
            {
                if ((this._serialNumber != value))
                {
                    string old = this._serialNumber;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnSerialNumberChanging(e);
                    this.OnPropertyChanging("SerialNumber", e, _serialNumberAttribute);
                    this._serialNumber = value;
                    this.OnSerialNumberChanged(e);
                    this.OnPropertyChanged("SerialNumber", e, _serialNumberAttribute);
                }
            }
        }
        
        /// <summary>
        /// Gets the IndividualProduct model for this type
        /// </summary>
        public new static Hsrm.DeepModeling.Warehouse.Warehouse.IIndividualProduct IndividualProductInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("https://example.org/products#//HaChi779")));
                }
                return ((Hsrm.DeepModeling.Warehouse.Warehouse.IIndividualProduct)(_classInstance));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static NMF.Models.Meta.IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("https://example.org/products#//HaChi779")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired when the SerialNumber property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> SerialNumberChanged;
        
        /// <summary>
        /// Gets fired before the SerialNumber property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> SerialNumberChanging;
        
        private static NMF.Models.Meta.ITypedElement RetrieveSerialNumberAttribute()
        {
            return ((NMF.Models.Meta.ITypedElement)(((NMF.Models.ModelElement)(Hsrm.DeepModeling.Warehouse.Products.Products.HaChi779.ClassInstance)).Resolve("serialNumber")));
        }
        
        /// <summary>
        /// Raises the SerialNumberChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnSerialNumberChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.SerialNumberChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the SerialNumberChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnSerialNumberChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.SerialNumberChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "SERIALNUMBER"))
            {
                return this.SerialNumber;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "SERIALNUMBER"))
            {
                this.SerialNumber = ((string)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "SERIALNUMBER"))
            {
                return new SerialNumberProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the IndividualProduct for this model element
        /// </summary>
        public override Hsrm.DeepModeling.Warehouse.Warehouse.IIndividualProduct GetIndividualProduct()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("https://example.org/products#//HaChi779")));
            }
            return ((Hsrm.DeepModeling.Warehouse.Warehouse.IIndividualProduct)(_classInstance));
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override NMF.Models.Meta.IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("https://example.org/products#//HaChi779")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the serialNumber property
        /// </summary>
        private sealed class SerialNumberProxy : ModelPropertyChange<IHaChi779, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public SerialNumberProxy(IHaChi779 modelElement) : 
                    base(modelElement, "serialNumber")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.SerialNumber;
                }
                set
                {
                    this.ModelElement.SerialNumber = value;
                }
            }
        }
    }
}
