//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hsrm.DeepModeling.Warehouse.Products.Products
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Linq;
    using NMF.Expressions;
    using NMF.Expressions.Linq;
    using NMF.Models;
    using NMF.Models.Meta;
    using NMF.Models.Collections;
    using NMF.Models.Expressions;
    using NMF.Collections.Generic;
    using NMF.Collections.ObjectModel;
    using NMF.Serialization;
    using NMF.Utilities;
    using NMF.Models.Repository;
    using Hsrm.DeepModeling.Warehouse.Warehouse;
    
    
    /// <summary>
    /// The public interface for Mate0815
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Mate0815))]
    [XmlDefaultImplementationTypeAttribute(typeof(Mate0815))]
    [ModelRepresentationClassAttribute("https://example.org/products#//Mate0815")]
    public interface IMate0815 : NMF.Models.IModelElement, Hsrm.DeepModeling.Warehouse.Warehouse.ISaleItem
    {
    }
}
