//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hsrm.DeepModeling.Warehouse.Warehouse
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Linq;
    using NMF.Expressions;
    using NMF.Expressions.Linq;
    using NMF.Models;
    using NMF.Models.Meta;
    using NMF.Models.Collections;
    using NMF.Models.Expressions;
    using NMF.Collections.Generic;
    using NMF.Collections.ObjectModel;
    using NMF.Serialization;
    using NMF.Utilities;
    using System.Collections.Specialized;
    using NMF.Models.Repository;
    
    
    /// <summary>
    /// The default implementation of the BulkProduct class
    /// </summary>
    [XmlNamespaceAttribute("https://multi-workshop.github.io/warehouse/nmeta")]
    [XmlNamespacePrefixAttribute("warehouse")]
    [ModelRepresentationClassAttribute("https://multi-workshop.github.io/warehouse/nmeta#//BulkProduct")]
    [DebuggerDisplayAttribute("BulkProduct {Name}")]
    public partial class BulkProduct : Product, IBulkProduct, NMF.Models.IModelElement
    {
        
        /// <summary>
        /// The backing field for the Quantity property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private int _quantity;
        
        private static Lazy<NMF.Models.Meta.ITypedElement> _quantityAttribute = new Lazy<NMF.Models.Meta.ITypedElement>(RetrieveQuantityAttribute);
        
        /// <summary>
        /// The backing field for the Stock property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private int _stock;
        
        private static Lazy<NMF.Models.Meta.ITypedElement> _stockAttribute = new Lazy<NMF.Models.Meta.ITypedElement>(RetrieveStockAttribute);
        
        private static NMF.Models.Meta.IClass _classInstance;
        
        /// <summary>
        /// The quantity property
        /// </summary>
        [DisplayNameAttribute("quantity")]
        [CategoryAttribute("BulkProduct")]
        [XmlElementNameAttribute("quantity")]
        [XmlAttributeAttribute(true)]
        public int Quantity
        {
            get
            {
                return this._quantity;
            }
            set
            {
                if ((this._quantity != value))
                {
                    int old = this._quantity;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnQuantityChanging(e);
                    this.OnPropertyChanging("Quantity", e, _quantityAttribute);
                    this._quantity = value;
                    this.OnQuantityChanged(e);
                    this.OnPropertyChanged("Quantity", e, _quantityAttribute);
                }
            }
        }
        
        /// <summary>
        /// The stock property
        /// </summary>
        [DisplayNameAttribute("stock")]
        [CategoryAttribute("BulkProduct")]
        [XmlElementNameAttribute("stock")]
        [XmlAttributeAttribute(true)]
        public int Stock
        {
            get
            {
                return this._stock;
            }
            set
            {
                if ((this._stock != value))
                {
                    int old = this._stock;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnStockChanging(e);
                    this.OnPropertyChanging("Stock", e, _stockAttribute);
                    this._stock = value;
                    this.OnStockChanged(e);
                    this.OnPropertyChanged("Stock", e, _stockAttribute);
                }
            }
        }
        
        /// <summary>
        /// Gets the ProductSpecification model for this type
        /// </summary>
        public new static IProductSpecification ProductSpecificationInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("https://multi-workshop.github.io/warehouse/nmeta#//BulkProduct")));
                }
                return ((IProductSpecification)(_classInstance));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static NMF.Models.Meta.IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("https://multi-workshop.github.io/warehouse/nmeta#//BulkProduct")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired when the Quantity property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> QuantityChanged;
        
        /// <summary>
        /// Gets fired before the Quantity property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> QuantityChanging;
        
        /// <summary>
        /// Gets fired when the Stock property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> StockChanged;
        
        /// <summary>
        /// Gets fired before the Stock property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> StockChanging;
        
        private static NMF.Models.Meta.ITypedElement RetrieveQuantityAttribute()
        {
            return ((NMF.Models.Meta.ITypedElement)(((NMF.Models.ModelElement)(Hsrm.DeepModeling.Warehouse.Warehouse.BulkProduct.ClassInstance)).Resolve("quantity")));
        }
        
        /// <summary>
        /// Raises the QuantityChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnQuantityChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.QuantityChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the QuantityChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnQuantityChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.QuantityChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static NMF.Models.Meta.ITypedElement RetrieveStockAttribute()
        {
            return ((NMF.Models.Meta.ITypedElement)(((NMF.Models.ModelElement)(Hsrm.DeepModeling.Warehouse.Warehouse.BulkProduct.ClassInstance)).Resolve("stock")));
        }
        
        /// <summary>
        /// Raises the StockChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnStockChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.StockChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the StockChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnStockChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.StockChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "QUANTITY"))
            {
                return this.Quantity;
            }
            if ((attribute == "STOCK"))
            {
                return this.Stock;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "QUANTITY"))
            {
                this.Quantity = ((int)(value));
                return;
            }
            if ((feature == "STOCK"))
            {
                this.Stock = ((int)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "QUANTITY"))
            {
                return Observable.Box(new QuantityProxy(this));
            }
            if ((attribute == "STOCK"))
            {
                return Observable.Box(new StockProxy(this));
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the ProductSpecification for this model element
        /// </summary>
        public override IProductSpecification GetProductSpecification()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("https://multi-workshop.github.io/warehouse/nmeta#//BulkProduct")));
            }
            return ((IProductSpecification)(_classInstance));
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override NMF.Models.Meta.IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("https://multi-workshop.github.io/warehouse/nmeta#//BulkProduct")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the quantity property
        /// </summary>
        private sealed class QuantityProxy : ModelPropertyChange<IBulkProduct, int>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public QuantityProxy(IBulkProduct modelElement) : 
                    base(modelElement, "quantity")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override int Value
            {
                get
                {
                    return this.ModelElement.Quantity;
                }
                set
                {
                    this.ModelElement.Quantity = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the stock property
        /// </summary>
        private sealed class StockProxy : ModelPropertyChange<IBulkProduct, int>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public StockProxy(IBulkProduct modelElement) : 
                    base(modelElement, "stock")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override int Value
            {
                get
                {
                    return this.ModelElement.Stock;
                }
                set
                {
                    this.ModelElement.Stock = value;
                }
            }
        }
    }
}
