//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hsrm.DeepModeling.Warehouse.Warehouse
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Linq;
    using NMF.Expressions;
    using NMF.Expressions.Linq;
    using NMF.Models;
    using NMF.Models.Meta;
    using NMF.Models.Collections;
    using NMF.Models.Expressions;
    using NMF.Collections.Generic;
    using NMF.Collections.ObjectModel;
    using NMF.Serialization;
    using NMF.Utilities;
    using System.Collections.Specialized;
    using NMF.Models.Repository;
    
    
    /// <summary>
    /// The public interface for ProductSpecification
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(ProductSpecification))]
    [XmlDefaultImplementationTypeAttribute(typeof(ProductSpecification))]
    [ModelRepresentationClassAttribute("https://multi-workshop.github.io/warehouse/nmeta#//ProductSpecification")]
    public interface IProductSpecification : NMF.Models.IModelElement, NMF.Models.Meta.IClass
    {
        
        /// <summary>
        /// The taxRate property
        /// </summary>
        [DisplayNameAttribute("taxRate")]
        [CategoryAttribute("ProductSpecification")]
        [XmlElementNameAttribute("taxRate")]
        [XmlAttributeAttribute(true)]
        double TaxRate
        {
            get;
            set;
        }
        
        /// <summary>
        /// The currency property
        /// </summary>
        [DisplayNameAttribute("currency")]
        [CategoryAttribute("ProductSpecification")]
        [XmlElementNameAttribute("currency")]
        [XmlAttributeAttribute(true)]
        string Currency
        {
            get;
            set;
        }
        
        /// <summary>
        /// The introductionDate property
        /// </summary>
        [TypeConverterAttribute(typeof(IsoDateTimeConverter))]
        [DisplayNameAttribute("introductionDate")]
        [CategoryAttribute("ProductSpecification")]
        [XmlElementNameAttribute("introductionDate")]
        [XmlAttributeAttribute(true)]
        DateTime IntroductionDate
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired when the TaxRate property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> TaxRateChanged;
        
        /// <summary>
        /// Gets fired before the TaxRate property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> TaxRateChanging;
        
        /// <summary>
        /// Gets fired when the Currency property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> CurrencyChanged;
        
        /// <summary>
        /// Gets fired before the Currency property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> CurrencyChanging;
        
        /// <summary>
        /// Gets fired when the IntroductionDate property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> IntroductionDateChanged;
        
        /// <summary>
        /// Gets fired before the IntroductionDate property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> IntroductionDateChanging;
    }
}
