//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hsrm.DeepModeling.Warehouse.Warehouse
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Linq;
    using NMF.Expressions;
    using NMF.Expressions.Linq;
    using NMF.Models;
    using NMF.Models.Meta;
    using NMF.Models.Collections;
    using NMF.Models.Expressions;
    using NMF.Collections.Generic;
    using NMF.Collections.ObjectModel;
    using NMF.Serialization;
    using NMF.Utilities;
    using System.Collections.Specialized;
    using NMF.Models.Repository;
    
    
    /// <summary>
    /// The public interface for Product
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Product))]
    [XmlDefaultImplementationTypeAttribute(typeof(Product))]
    [ModelRepresentationClassAttribute("https://multi-workshop.github.io/warehouse/nmeta#//Product")]
    public interface IProduct : NMF.Models.IModelElement, NMF.Models.Meta.IMetaElement
    {
        
        /// <summary>
        /// The salesPrice property
        /// </summary>
        [DisplayNameAttribute("salesPrice")]
        [CategoryAttribute("Product")]
        [XmlElementNameAttribute("salesPrice")]
        [XmlAttributeAttribute(true)]
        double SalesPrice
        {
            get;
            set;
        }
        
        /// <summary>
        /// The recommends property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [DisplayNameAttribute("recommends")]
        [CategoryAttribute("Product")]
        [XmlElementNameAttribute("recommends")]
        [XmlAttributeAttribute(true)]
        [ConstantAttribute()]
        ICollectionExpression<IProduct> Recommends
        {
            get;
        }
        
        /// <summary>
        /// Gets fired when the SalesPrice property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SalesPriceChanged;
        
        /// <summary>
        /// Gets fired before the SalesPrice property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SalesPriceChanging;
        
        /// <summary>
        /// Gets the ProductSpecification for this model element
        /// </summary>
        IProductSpecification GetProductSpecification();
    }
}
