//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hsrm.DeepModeling.Warehouse.Warehouse
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Linq;
    using NMF.Expressions;
    using NMF.Expressions.Linq;
    using NMF.Models;
    using NMF.Models.Meta;
    using NMF.Models.Collections;
    using NMF.Models.Expressions;
    using NMF.Collections.Generic;
    using NMF.Collections.ObjectModel;
    using NMF.Serialization;
    using NMF.Utilities;
    using System.Collections.Specialized;
    using NMF.Models.Repository;
    
    
    /// <summary>
    /// The public interface for SalePrice
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(SalePrice))]
    [XmlDefaultImplementationTypeAttribute(typeof(SalePrice))]
    [ModelRepresentationClassAttribute("https://multi-workshop.github.io/warehouse/nmeta#//SalePrice")]
    public interface ISalePrice : NMF.Models.IModelElement
    {
        
        /// <summary>
        /// The reducedPrice property
        /// </summary>
        [DisplayNameAttribute("reducedPrice")]
        [CategoryAttribute("SalePrice")]
        [XmlElementNameAttribute("reducedPrice")]
        [XmlAttributeAttribute(true)]
        double ReducedPrice
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired when the ReducedPrice property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ReducedPriceChanged;
        
        /// <summary>
        /// Gets fired before the ReducedPrice property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ReducedPriceChanging;
    }
}
